<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Results &amp; Discussion – Urban Happiness Prediction</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-1286455570d26e9a8c2ec2f040580532.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../analysis/4-results.html">Results</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../images/logo.svg" alt="" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="../images/logo.svg" alt="" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Methodology</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analysis/1-data-collection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Collection</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analysis/2-semantic-segmentation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Semantic Segmentation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analysis/3-pu-learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PU Learning Model</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analysis/4-results.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Results</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#how-well-does-the-model-perform" id="toc-how-well-does-the-model-perform" class="nav-link active" data-scroll-target="#how-well-does-the-model-perform">How Well Does the Model Perform?</a></li>
  <li><a href="#what-predicts-happiness" id="toc-what-predicts-happiness" class="nav-link" data-scroll-target="#what-predicts-happiness">What Predicts Happiness?</a></li>
  <li><a href="#the-owner-occupancy-paradox" id="toc-the-owner-occupancy-paradox" class="nav-link" data-scroll-target="#the-owner-occupancy-paradox">The Owner-Occupancy Paradox</a></li>
  <li><a href="#visual-environment-what-you-see-matters" id="toc-visual-environment-what-you-see-matters" class="nav-link" data-scroll-target="#visual-environment-what-you-see-matters">Visual Environment: What You See Matters</a></li>
  <li><a href="#socioeconomic-context" id="toc-socioeconomic-context" class="nav-link" data-scroll-target="#socioeconomic-context">Socioeconomic Context</a></li>
  <li><a href="#mapping-happiness-across-philadelphia" id="toc-mapping-happiness-across-philadelphia" class="nav-link" data-scroll-target="#mapping-happiness-across-philadelphia">Mapping Happiness Across Philadelphia</a></li>
  <li><a href="#limitations-what-this-study-cannot-tell-us" id="toc-limitations-what-this-study-cannot-tell-us" class="nav-link" data-scroll-target="#limitations-what-this-study-cannot-tell-us">Limitations: What This Study Cannot Tell Us</a>
  <ul class="collapse">
  <li><a href="#the-problem-of-28-points" id="toc-the-problem-of-28-points" class="nav-link" data-scroll-target="#the-problem-of-28-points">The Problem of 28 Points</a></li>
  <li><a href="#the-gap-between-happiness-and-its-proxy" id="toc-the-gap-between-happiness-and-its-proxy" class="nav-link" data-scroll-target="#the-gap-between-happiness-and-its-proxy">The Gap Between Happiness and Its Proxy</a></li>
  <li><a href="#census-data-is-too-coarse" id="toc-census-data-is-too-coarse" class="nav-link" data-scroll-target="#census-data-is-too-coarse">Census Data Is Too Coarse</a></li>
  <li><a href="#happiness-isnt-always-about-environment" id="toc-happiness-isnt-always-about-environment" class="nav-link" data-scroll-target="#happiness-isnt-always-about-environment">Happiness Isn’t Always About Environment</a></li>
  <li><a href="#temporal-blindness" id="toc-temporal-blindness" class="nav-link" data-scroll-target="#temporal-blindness">Temporal Blindness</a></li>
  <li><a href="#sky-ratio-vs.-sky-view-factor" id="toc-sky-ratio-vs.-sky-view-factor" class="nav-link" data-scroll-target="#sky-ratio-vs.-sky-view-factor">Sky Ratio vs.&nbsp;Sky View Factor</a></li>
  <li><a href="#correlation-not-causation" id="toc-correlation-not-causation" class="nav-link" data-scroll-target="#correlation-not-causation">Correlation, Not Causation</a></li>
  </ul></li>
  <li><a href="#implications-for-urban-planning" id="toc-implications-for-urban-planning" class="nav-link" data-scroll-target="#implications-for-urban-planning">Implications for Urban Planning</a></li>
  <li><a href="#future-directions" id="toc-future-directions" class="nav-link" data-scroll-target="#future-directions">Future Directions</a></li>
  <li><a href="#what-weve-learned" id="toc-what-weve-learned" class="nav-link" data-scroll-target="#what-weve-learned">What We’ve Learned</a></li>
  <li><a href="#a-final-reflection" id="toc-a-final-reflection" class="nav-link" data-scroll-target="#a-final-reflection">A Final Reflection</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/yourusername/urban-happiness/blob/main/analysis/4-results.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content column-body" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Results &amp; Discussion</h1>
<p class="subtitle lead">Key Findings and Urban Planning Implications</p>
</div>



<div class="quarto-title-meta column-body">

    
  
    
  </div>
  


</header>


<section id="how-well-does-the-model-perform" class="level2">
<h2 class="anchored" data-anchor-id="how-well-does-the-model-perform">How Well Does the Model Perform?</h2>
<p>Our PU Learning approach achieved strong predictive performance, with Logistic Regression reaching an AUC of 0.968—meaning if we randomly select one happiness point and one reliable negative, the model correctly ranks them 96.8% of the time.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../images/roc_curve.png" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>ROC Curves showing model performance</figcaption>
</figure>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th>Logistic Regression</th>
<th>Random Forest</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>AUC-ROC</td>
<td>0.968 ± 0.013</td>
<td>0.939 ± 0.045</td>
</tr>
<tr class="even">
<td>Training samples</td>
<td>28 positive + ~9,000 negative</td>
<td></td>
</tr>
<tr class="odd">
<td>Features</td>
<td>13 (6 visual + 7 socioeconomic)</td>
<td></td>
</tr>
</tbody>
</table>
<p>The high AUC suggests happiness points are systematically different from random street locations in measurable ways. But as we’ll discuss later, this strong performance comes with important caveats.</p>
<hr>
</section>
<section id="what-predicts-happiness" class="level2">
<h2 class="anchored" data-anchor-id="what-predicts-happiness">What Predicts Happiness?</h2>
<p>The lollipop chart visualizes the direction and magnitude of each feature’s effect:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../images/lollipop_chart.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Feature Effects on Happiness (Lollipop Chart)</figcaption>
</figure>
</div>
<p><strong>Building Ratio</strong> emerges as the strongest positive predictor (+1.00), indicating happiness points cluster in denser urban areas rather than sparse residential neighborhoods. <strong>Owner Occupied Rate</strong> shows the strongest negative effect (-2.10)—our most counterintuitive finding. <strong>College Education</strong> and <strong>Sky Ratio</strong> are strong positive predictors, while <strong>Poverty Rate</strong> and <strong>Road Ratio</strong> pull strongly negative.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../images/rose_chart.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Feature Importance Rose Chart</figcaption>
</figure>
</div>
<p>The rose chart offers another view: socioeconomic factors (owner-occupancy, poverty, education) have larger magnitudes than most visual features. This hints that neighborhood context matters as much as—perhaps more than—what you can see in a photograph.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 22%">
<col style="width: 17%">
<col style="width: 4%">
<col style="width: 8%">
<col style="width: 22%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Rank</th>
<th>Positive Factors</th>
<th>Coefficient</th>
<th></th>
<th>Rank</th>
<th>Negative Factors</th>
<th>Coefficient</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>building_ratio</td>
<td>+1.00</td>
<td></td>
<td>1</td>
<td>pct_owner_occupied</td>
<td>-2.10</td>
</tr>
<tr class="even">
<td>2</td>
<td>pct_college</td>
<td>+0.70</td>
<td></td>
<td>2</td>
<td>poverty_rate</td>
<td>-1.28</td>
</tr>
<tr class="odd">
<td>3</td>
<td>sky_ratio</td>
<td>+0.58</td>
<td></td>
<td>3</td>
<td>road_ratio</td>
<td>-1.23</td>
</tr>
<tr class="even">
<td>4</td>
<td>median_income</td>
<td>+0.18</td>
<td></td>
<td>4</td>
<td>vehicle_ratio</td>
<td>-0.29</td>
</tr>
<tr class="odd">
<td>5</td>
<td>green_view_index</td>
<td>+0.06</td>
<td></td>
<td>5</td>
<td>person_ratio</td>
<td>-0.24</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="the-owner-occupancy-paradox" class="level2">
<h2 class="anchored" data-anchor-id="the-owner-occupancy-paradox">The Owner-Occupancy Paradox</h2>
<p>The most striking finding is the strong <strong>negative</strong> relationship between homeownership rate and happiness. Traditional urban planning often equates high homeownership with neighborhood quality—homeowners invest in maintenance, stable populations build community, crime rates tend to be lower. Yet our model finds the opposite relationship.</p>
<p>We hypothesize that <strong>what makes a neighborhood good for living differs from what makes a place feel happy</strong>. High-ownership neighborhoods are typically quiet, safe, single-use residential areas—pleasant to live in, but not places you’d visit for joy. They’re car-dependent, with few spontaneous social encounters. Happiness points, by contrast, cluster in mixed-use urban areas: walkable, with nearby amenities, active street life, diverse activities and people.</p>
<p>The data supports this interpretation:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th>Happiness Points</th>
<th>City Average</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Owner-occupancy</td>
<td>34.2%</td>
<td>52.3%</td>
</tr>
<tr class="even">
<td>Building ratio</td>
<td>21.3%</td>
<td>18.8%</td>
</tr>
<tr class="odd">
<td>Road ratio</td>
<td>19.6%</td>
<td>22.3%</td>
</tr>
</tbody>
</table>
<p>Happiness points sit in areas with 18 percentage points lower owner-occupancy, 2.5 points higher building density, and 2.7 points lower road coverage. This pattern describes walkable, urban neighborhoods rather than suburban residential streets.</p>
<hr>
</section>
<section id="visual-environment-what-you-see-matters" class="level2">
<h2 class="anchored" data-anchor-id="visual-environment-what-you-see-matters">Visual Environment: What You See Matters</h2>
<p><strong>Sky visibility</strong> emerged as a significant positive predictor (+0.58). Visible sky reduces feelings of confinement; better daylight improves mood; tall buildings blocking the sky create oppressive urban canyons. This aligns with decades of environmental psychology research.</p>
<p><strong>Building density</strong> predicts higher happiness (+1.00)—perhaps counterintuitively. But dense areas have more amenities, services, activities, and social interaction opportunities. The key is that both building_ratio and sky_ratio are positive predictors simultaneously, suggesting happiness is found in <strong>moderately dense</strong> environments: enough urban vitality to be interesting, not so much as to feel oppressive. Mid-rise neighborhoods, not sprawling suburbs or canyon-like downtowns.</p>
<p><strong>Road coverage</strong> is a strong negative predictor (-1.23). More road means less space for pedestrians, bikes, and greenery. It indicates traffic noise and pollution exposure. Wide roads create barriers to crossing, fragmenting neighborhoods. The “livable streets” movement has long argued that car-centric design diminishes quality of life; our data supports this.</p>
<hr>
</section>
<section id="socioeconomic-context" class="level2">
<h2 class="anchored" data-anchor-id="socioeconomic-context">Socioeconomic Context</h2>
<p><strong>Education and income</strong> both positively predict happiness. Higher-income areas tend to have better maintenance, higher-quality amenities, and more investment in public spaces. There’s also likely a selection effect: survey respondents (university students) may gravitate toward areas similar to their own neighborhoods.</p>
<p><strong>Poverty rate</strong> shows a strong negative effect (-1.28), reflecting the accumulated disadvantages of high-poverty neighborhoods: deferred maintenance, visible decay, safety concerns, and fewer commercial establishments. Happiness, it seems, is not equally distributed across the city.</p>
<hr>
</section>
<section id="mapping-happiness-across-philadelphia" class="level2">
<h2 class="anchored" data-anchor-id="mapping-happiness-across-philadelphia">Mapping Happiness Across Philadelphia</h2>
<p>After scoring all ~40,000 points, we can visualize predicted happiness across the city:</p>
<div style="width: 100%; height: 600px; border-radius: 12px; overflow: hidden; box-shadow: 0 8px 32px rgba(0,0,0,0.3);">
<iframe src="../images/kriging_happiness_map.html" width="100%" height="100%" style="border: none;">
</iframe>
</div>
<p><em>Interactive map: Drag to pan, scroll to zoom. Adjust layer opacity with the slider.</em></p>
<p>The spatial pattern is clear. Highest scores concentrate in Center City, University City, Fairmount, and Northern Liberties—dense, mixed-use, walkable neighborhoods. Moderate scores appear in inner-ring neighborhoods with mixed uses. Lowest scores mark outer residential areas, industrial zones, and highway corridors.</p>
<p>This isn’t surprising given our model’s coefficients, but seeing it mapped across the city makes the pattern visceral. The happy places form a connected archipelago in the urban core, surrounded by a sea of lower-scoring residential and industrial areas.</p>
<hr>
</section>
<section id="limitations-what-this-study-cannot-tell-us" class="level2">
<h2 class="anchored" data-anchor-id="limitations-what-this-study-cannot-tell-us">Limitations: What This Study Cannot Tell Us</h2>
<p>Strong model performance doesn’t mean we’ve solved urban happiness. Several limitations deserve honest acknowledgment.</p>
<section id="the-problem-of-28-points" class="level3">
<h3 class="anchored" data-anchor-id="the-problem-of-28-points">The Problem of 28 Points</h3>
<p>With only 28 positive samples, statistical power is limited. Unusual characteristics of individual points may unduly influence results. Cross-validation produces small validation sets of just 5-6 positives per fold. We can identify broad patterns, but detecting subtle effects is beyond our reach. A study with hundreds or thousands of happiness points would be far more robust.</p>
</section>
<section id="the-gap-between-happiness-and-its-proxy" class="level3">
<h3 class="anchored" data-anchor-id="the-gap-between-happiness-and-its-proxy">The Gap Between Happiness and Its Proxy</h3>
<p>We couldn’t capture street view imagery at the exact happiness point locations. Instead, we used the nearest sampling point’s imagery—sometimes tens or hundreds of meters away. Some happiness points are “secret gardens” that students discovered: hidden courtyards, rooftop terraces, tucked-away benches. These intimate spaces don’t appear in street-level panoramas at all. This spatial mismatch may explain why <strong>green view index shows such weak predictive power</strong> (+0.06). The actual happy places might be far greener than what our proxy images capture.</p>
</section>
<section id="census-data-is-too-coarse" class="level3">
<h3 class="anchored" data-anchor-id="census-data-is-too-coarse">Census Data Is Too Coarse</h3>
<p>Census tract-level socioeconomic data averages over roughly 4,100 residents per tract. A street corner in a nominally wealthy tract may actually be surrounded by lower-income residents, but our data cannot capture this intra-tract variation. We’re assigning neighborhood-level characteristics to point-level observations—an ecological fallacy risk that’s difficult to avoid without finer-grained data.</p>
</section>
<section id="happiness-isnt-always-about-environment" class="level3">
<h3 class="anchored" data-anchor-id="happiness-isnt-always-about-environment">Happiness Isn’t Always About Environment</h3>
<p>Our model assumes happiness derives from measurable environmental and socioeconomic features. But some places are happy not because of what they look like, but because of what happened there. A nondescript bench where someone had their first kiss. An ordinary-looking café where friends gather every Sunday. A street corner that reminds someone of childhood. These <strong>places of memory</strong> can bring profound happiness despite being visually unremarkable. No amount of semantic segmentation can capture why a place matters to someone.</p>
</section>
<section id="temporal-blindness" class="level3">
<h3 class="anchored" data-anchor-id="temporal-blindness">Temporal Blindness</h3>
<p>Our analysis uses static data: street view images from a single moment, Census data averaged over five years. We don’t account for seasonal variation—and this matters more than it might seem. Philadelphia’s Green View Index plummets in winter when deciduous trees are bare. A street that feels lush and alive in July can look stark and gray in January. Should we process winter and summer imagery separately? Our current approach treats them identically, potentially washing out seasonal effects. We also miss weekly and daily rhythms: the same plaza might feel vibrant on a Saturday afternoon and desolate on a Tuesday morning.</p>
</section>
<section id="sky-ratio-vs.-sky-view-factor" class="level3">
<h3 class="anchored" data-anchor-id="sky-ratio-vs.-sky-view-factor">Sky Ratio vs.&nbsp;Sky View Factor</h3>
<p>We measure simple sky pixel proportion, but the more sophisticated <strong>Sky View Factor (SVF)</strong> accounts for hemispherical projection and better represents human perception of openness. SVF would weight overhead sky more heavily than sky near the horizon, matching how we actually experience urban space. This is a methodological improvement worth pursuing in future work.</p>
</section>
<section id="correlation-not-causation" class="level3">
<h3 class="anchored" data-anchor-id="correlation-not-causation">Correlation, Not Causation</h3>
<p>This is a correlational study. We cannot claim that building density <em>causes</em> happiness. The relationship could be confounded (both caused by a third factor), reversed (happy people might seek out dense areas), or more complex than our linear model can capture.</p>
<hr>
</section>
</section>
<section id="implications-for-urban-planning" class="level2">
<h2 class="anchored" data-anchor-id="implications-for-urban-planning">Implications for Urban Planning</h2>
<p>Despite these limitations, our findings suggest several considerations for those who shape cities.</p>
<p><strong>Rethinking density</strong>: The simultaneous positive effects of building density and sky visibility suggest an optimal density range. Mid-rise development, setback requirements to preserve street-level openness, and rooftop gardens might capture both urban vitality and psychological comfort.</p>
<p><strong>Reducing car dominance</strong>: The negative effects of road and vehicle coverage support road diets that convert vehicle lanes to pedestrian or green space, traffic calming, pedestrianization of key streets, and parking reform that reduces surface lots.</p>
<p><strong>Addressing equity</strong>: The strong negative effect of poverty rate highlights that happiness is not equally distributed. Investing in high-poverty neighborhoods—parks, streetscaping, façade improvements—could begin to address this imbalance.</p>
<p><strong>Embracing mixed-use</strong>: The owner-occupancy paradox suggests purely residential areas, however safe and well-maintained, may not generate happiness. Mixed-use zoning that allows retail, services, and housing together; 15-minute neighborhoods where daily needs are within walking distance; “third places” like cafés and libraries that foster social interaction—these may matter more than homeownership rates for urban happiness.</p>
<hr>
</section>
<section id="future-directions" class="level2">
<h2 class="anchored" data-anchor-id="future-directions">Future Directions</h2>
<p>This study opens several avenues for future research. <strong>Expanding positive samples</strong> through crowdsourced happiness mapping could provide hundreds or thousands of points, dramatically improving statistical power. <strong>Temporal analysis</strong> comparing street view images across seasons and years would reveal whether happiness correlates with greenery only when trees are leafed out. <strong>Multi-city comparison</strong> would test whether the same features predict happiness in different urban contexts. <strong>Sky View Factor calculation</strong> would provide a more perceptually accurate measure of openness. And <strong>qualitative validation</strong>—actually interviewing respondents about why they chose specific locations—would ground our quantitative findings in human experience.</p>
<hr>
</section>
<section id="what-weve-learned" class="level2">
<h2 class="anchored" data-anchor-id="what-weve-learned">What We’ve Learned</h2>
<p>Urban happiness is measurable and predictable from environmental features—at least partially. Sky visibility and building density correlate positively with happiness; road coverage correlates negatively. High-homeownership neighborhoods are less likely to contain happiness points, suggesting “livability” and “happiness” are distinct concepts. Education and income predict happiness; poverty predicts its absence.</p>
<p>But the numbers only tell part of the story. Some happy places are hidden from street view cameras. Some happiness comes from memory, not environment. Some variation is seasonal, daily, personal.</p>
<hr>
</section>
<section id="a-final-reflection" class="level2">
<h2 class="anchored" data-anchor-id="a-final-reflection">A Final Reflection</h2>
<p>This project demonstrates how street-level imagery and machine learning can be combined to study urban emotion at scale. It extends psychological theories of place and well-being into a computational framework, transforming visual data into measurable indicators of how cities make people feel.</p>
<p>But we should be humble about what we’ve captured. Everyone living in Philadelphia has their own list of happy places, and there is never a single right answer to what happiness means. The Cat Park with its friendly felines, the bustling atmosphere of Mango Mango Desserts, the cozy corner of Maison Sweet where you might stay longer than planned—these are not places we can fully quantify. A grandmother’s kitchen. A spot by the river where someone proposed. The bench where you sat crying after a breakup and a stranger offered you a tissue.</p>
<p>Happiness is environmental, yes. But it’s also biographical. Our models can find the patterns that connect happy places; they cannot explain why a particular place became <em>your</em> happy place.</p>
<p>What we hope is that by mapping these patterns, we might help create more spaces where happiness can happen—even if we can’t predict exactly who will find joy there, or why.</p>
<p><strong>A lot of things need fixing in Philly, but there are a lot of good things here.</strong></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/yourusername/urban-happiness/blob/main/analysis/4-results.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li></ul></div></div></div></footer></body></html>